# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2016-07-15 17:17
from __future__ import unicode_literals

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('auth', '0007_alter_validators_add_error_messages'),
    ]

    operations = [
        migrations.CreateModel(
            name='Driver',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=128)),
            ],
        ),
        migrations.CreateModel(
            name='Manager',
            fields=[
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, primary_key=True, serialize=False, to=settings.AUTH_USER_MODEL)),
                ('name', models.CharField(max_length=30)),
            ],
        ),
        migrations.CreateModel(
            name='Manufacture',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=30, unique=True)),
            ],
        ),
        migrations.CreateModel(
            name='UseControl',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date_started', models.DateTimeField(auto_now_add=True)),
                ('date_ended', models.DateTimeField(blank=True, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Vehicle',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=30)),
                ('description', models.TextField(null=True)),
                ('license_plate', models.CharField(max_length=7)),
                ('manufacture_year', models.DateField()),
                ('is_active', models.BooleanField(default=True)),
                ('manufaturer', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='resources.Manufacture')),
                ('usecontrols', models.ManyToManyField(through='resources.UseControl', to='resources.Driver')),
            ],
        ),
        migrations.AddField(
            model_name='usecontrol',
            name='Vehicle',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='resources.Vehicle'),
        ),
        migrations.AddField(
            model_name='usecontrol',
            name='driver',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='resources.Driver'),
        ),
    ]
